version: "3.8"

services:
  # Backend API
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    environment:
      - CLARIFAI_API_KEY=4d3747c0593249f9b92935d3a298ab0d
      # - DATABASE_URL=postgres://opphniiakwxelg:21d1ebc8eb694f24b329f4dd33bf71c8d81f4634eb2d9b8f98c39ff80f6501a7@ec2-3-234-169-147.compute-1.amazonaws.com:5432/dctqbmr2ocj0pf
      - DATABASE_URL=postgres://dongyun:secret@postgres:5432/smart-brain
      - REDIS_URI=redis://redis:6379
    volumes:
      - ./:/usr/src/smart-brain-api

  # Postgres
  postgres:
    # container_name: postgres
    environment:
      POSTGRES_USER: dongyun
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
