version: "3.8"

services:
  # Backend API
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    environment:
      - REDIS_URI=redis://redis:6379
    volumes:
      - ./:/usr/src/smart-brain-api

  # Postgres
  postgres:
    # container_name: postgres
    environment:
      POSTGRES_USER: dongyun
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5433:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6380:6379"
